language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - SYMFONY_VERSION=2.2.*
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.4.*
  - SYMFONY_VERSION='dev-master symfony/event-dispatcher:~2.5@dev symfony/http-kernel:~2.5@dev'

before_script:
  - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update
  - composer install --prefer-dist --dev

script: phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
