sudo: false

language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  - SYMFONY_VERSION="~2.3"
  - SYMFONY_VERSION="~2.7"
  - SYMFONY_VERSION="~2.8"
  - SYMFONY_VERSION="~3.0"

matrix:
  exclude:
    - php: 5.3
      env: SYMFONY_VERSION="~3.0"
    - php: 5.4
      env: SYMFONY_VERSION="~3.0"

before_script:
  - if [[ "$TRAVIS_PHP_VERSION" == "hhvm" ]]; then echo -e '\nhhvm.libxml.ext_entity_whitelist = "file"' | tee -a /etc/hhvm/php.ini; fi
  - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update
  - composer install --prefer-dist --dev

script: vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
